### PR TITLE
Use travis.ci to build

### PR DESCRIPTION
**Pull request by briprowe**
Let's use [travis](https://docs.travis-ci.com/user/getting-started/) to build our open source projects.

### CODE REVIEW

**Comment by fraburnham** [comment]
This PR is doing too much. Please open a PR for each of your changes.

**Comment by fraburnham** [comment]
:+1:

**Comment by briprowe** [comment]
haha

**Comment by briprowe** [comment]
@whalesalad @tvanhens Thoughts?

**Comment by briprowe** [comment]
When you get a spare moment, of course.

**Comment by whalesalad** [comment]
LGTM :ship: :shipit: :+1: :boom:

**Pull request merged**
